export const questions = [
  "Harry is in danger if you are a member of Dumbledores Army take a drink",
  "Voldemort is back All Death Eaters cheers then take a drink",
  "Ministry Of Magic has been attacked all those members that are a part of the Ministry Of Magic take a drink",
  "Secret keeper, the Oder is under attack to keep it safe all members of Order Of The Phoenix have to say ‘Sherbet Lemon” before each drink (one drink penalty each time not observed)",
  "Fred Weasley has jinxed you drink the drink is now stuck to your face at all times until another Weasley is pulled (one drink penalty each time caught not with a drink to face)",
  "Just like George Weasley, you can not hear out of one ear cup one ear until another Weasley is pulled (one drink penalty each time caught not cupping ear)",
  "You and Neville Longbottom love plants each time you speak you must complete a plant (one drink penalty each time not observed)",
  "Wormtail face you have been jinxed with rat face (make a face like a rat two front teeth showing at all times (one drink penalty each time caught not doing it)",
  "The Centaur don’t like humans if you are a human take a drink",
  "The magic flying car has been illegally spotted the last person to say “obliviate” drinks twice",
  "Hufflepuff has won the quidditch match (if a member of Hufflepuff take a drink and high five all other members of Hufflepuff note if you can’t high five take two drinks)",
  "Gryffindor has won the quidditch match (if a member of Gryffindor take a drink and high five all other members of Gryffindor note if you can’t high five take two drinks)",
  "Slytherin has won the quidditch match (if a member of Slytherin take a drink and high five all other members of Slytherin note if you can’t high five take two drinks)",
  "Ravenclaw has won the quidditch match (if a member of Ravenclaw take a drink and high five all other members of Ravenclaw note if you can’t high five take two drinks)",
  "OWL’s name a spell if you can not name one spell then take a drink that person is now a troll and must keep a slack jaw open mouth at all times until the game mentions Ravenclaw (one drink penalty each time not observed)",
  "Twins! They fight together but also get in trouble together pick a person to be your drinking mate each either of you has to drink both the twin has to drink until another Weasley is pulled",
  "Molly Weasley, WHAT A MESS! You must pretend to polish the table or playing surface until another Weasley is pulled (one drink penalty each time not observed)",
  "Attack at Hogwarts if you are a student of Ravenclaw Gryffindor or Hufflepuff take a drink",
  "Dueling champion each time you say Avada Kedavra and point at a person they must reply Expelliarmus this goes until a house name is mentioned in the game (one drink penalty each time not replied)",
  "After-hours party all non-students take a drink",
  "Marvolo Gaunt's Ring your right hand has been cursed by the Horcrux you can only touch any drink with your left hand until the sword of Gryffindor comes out(one drink penalty each time not observed)",
  "Veritaserum the player to your right will get to ask you a question if you don’t answer truly take 5 drinks",
  "Get Salazar Slytherin's Locket by drinking in a waterfall fashion starting with you start drinking everyone starts with you once you stop the next person in line can stop once they stop the next person can stop and so on.",
  "Rowena Ravenclaw's Diadem the person to your left will find something to be your Diadem. Wear this with pride until the sword of Gryffindor (one drink penalty each time not observed)",
  "The sword of Gryffindor clears all effects from Horcruxes ",
  "FELIX Felicis your lucky day remove any effect given to you by any card and give it to someone else (if you have no effects consider yourself already lucky and take one drink)",
  "Fenrir Greyback has bitten you each time you have to drink you must howl (one drink penalty each time not observed)",
  "Ravenclaw quiz time go in a circle and name a Ravenclaw member or drink no repeats go until 2 can people can not name one ",
  "Gryffindor quiz time go in a circle and name a Gryffindor member or drink no repeats go until 2 can people can not name one",
  "Slytherin quiz time go in a circle and name a Slytherin member or drink no repeats go until 2 can people can not name one",
  "Hufflepuff quiz time go in a circle and name a Hufflepuff member or drink no repeats go until 2 can people can not name one",
  "If you are a Death  Eater touch your forearm and say “Morsmordre” if you are the last death eater to do so than drink (if you are the only death eater to do so then everyone else drinks twice)",
  "Ministry of magic if you are the current player and you are a Ministry member can add over remove one effect.",
  "Draco Malfoy called you a made fun of your blood status if you are not pure-blood take a drink but also pick on a pure-blood person to drink with you",
  "If you did not go to Hogwarts School of Witchcraft and Wizardry drink",
  "All members of Dumbledores Army just got caught by Dolores Umbridge take a drink for each member caught",
  "Weasley love position you must complement the person across from you each time that person speaks  until another Weasley is pulled (one drink penalty each time not observed)",
  "Weasley  Peruvian Instant Darkness Powder you must play with your eyes shut until another Weasley is pulled (one drink penalty each time not observed)",
  "Order of the Phoenix if you are a member then pick a non-member they drink twice",
  "Go in a circle naming instructors at Hogwarts until someone cant’ name one that person drinks once",
  "Flying lessons you are now fixed to a broom and must pretend to fly it when you need to get up or move (five drink penalty each time not observed)",
  "Son of a snitch last person touching something gold has to take 4 drinks",
  "Keeper put 3 cups near you if anyone can get any item into the cup you must drink for each item (goes until a house wins a quidditch game if your house pas the keeper cups to a person in a house that is not yours)",
  "If your blood status is unknown drink once",
  "If you are a pure-blood drink once for each non-pure blood",
  "If you are not a human lets party like an animal you must embody the traits of the species (one drink penalty each time not observed)",
  "Grab a timer for Dobby find a pair of socks and present them to the person across from you and say 'your a free elf' you have 13 seconds each second over is an additional drink maxed out at 7",
  "Name all the Horcruxes, drink for each you can not name ",
  "The beater, any time people address you you have to pretend to beat the comment away from you to the person to the left or right of you that person then has to duck (if you fail to beat the addressed statement away you drink twice if the person to the left or right pending on the beating motion didn’t duck they drink once) ",
  "The seeker, you must pass something to another player each time you are addressed (if you fail to pass something drink 5 times if they drop the item both of you drink once) ",
  "Get a timer ready, Mad-Eye, any nonmember of the order of the phoenix must find something that starts with the letter I out of arms reach from you right now and return to the game. The last person to do so drinks twice ",
  "Wrackspurts, when the person to your left is talking to you, must swat the Wrackspurts away from above that person head (one drink penalty each time not observed)",
  "Time Turner… in a circle starting with the person to your right will a gesture you must repeat that gesture and one additional gesture and pass it to the left that person will reap the two actions and add on this will go on until some messes up (that person will drink for each gesture missed)",
  "Potions Master you must find a student to insult if non are playing then everyone drinks once ",
  "Fluffy, you and the two people to you left and right are now joined get shoulder to shoulder you must stay shoulder to shoulder until one of the houses comes up.  (one drink penalty each time not observed)",
  "It’s LeviOsaaa, each time the person to you left speaks you must correct them with an over the pronunciation of the last thing they said (one drink penalty each time not observed)",
  "Death Eaters unit! Every player that is not a death eater must drink for each death eater playing.",
  "If you are not part of any group pick a group all members of that group must drink for each member. (Death Eater, Dumbledores Army, Order Of The Phoenix, Ministry Of Magic)",
  "Boggart, go in a circle starting with your left that person must name something they are afraid of you must act it out the next person will say “ridiculous” and name something else if you fail to act drink if they fail to say “ridiculous” they drink this stops when it comes back to you",
  "Get the timer out and set to 1:30 I solemnly swear I am up to no good, reenact a time you got in trouble without words  the other players must guess what you did you get in trouble (if no one can guess it than everyone drinks) ",
  "If you are not a member of Dumbledores Army drink once",
  "Weasley ageing position now you must act as if you turned 99 years old  until another Weasley is pulled (one drink penalty each time not observed",
  "All Order Of The Phoenix and  Death Eater members must face off go back and forth naming spells until a side can’t name a spell that side drinks for each member of the other side ",
  "The person across from you is Buckbeak if you don’t bow to each before standing you both must drink one ",
  "Tri wizard cup, the person across from you is a dragon the people to you left and right are competing against you the dragon must name an item in the room, not on a person or in reach and the first person to touch that item is the winner the other two members drink 3 times  ",
  "Master of death, you are free from all and any effects until your next turn",
]